# Makefile.in generated by automake 1.16.1 from Makefile.am.
# fuzz/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


# CC=/usr/bin/clang
# CXX=/usr/bin/clang++

fuzzing: fuzz_tests/fuzz.c fuzz_tests/xpath.c fuzz_tests/uri.c fuzz_tests/html.c fuzz_tests/xml.c fuzz_tests/regexp.c
	${CC} ${CFLAGS} ${FUZZ_TEST_CFLAGS} ${FUZZ_TEST_LDFLAGS} -o fuzz_xml fuzz_tests/xml.c fuzz_tests/fuzz.c -I_/include/libxml2 -L_/lib -lxml2
	${CC} ${CFLAGS} ${FUZZ_TEST_CFLAGS} ${FUZZ_TEST_LDFLAGS} -o fuzz_xpath fuzz_tests/xpath.c fuzz_tests/fuzz.c -I_/include/libxml2 -L_/lib -lxml2
	${CC} ${CFLAGS} ${FUZZ_TEST_CFLAGS} ${FUZZ_TEST_LDFLAGS} -o fuzz_uri fuzz_tests/uri.c fuzz_tests/fuzz.c -I_/include/libxml2 -L_/lib -lxml2
	${CC} ${CFLAGS} ${FUZZ_TEST_CFLAGS} ${FUZZ_TEST_LDFLAGS} -o fuzz_html fuzz_tests/html.c fuzz_tests/fuzz.c -I_/include/libxml2 -L_/lib -lxml2
	${CC} ${CFLAGS} ${FUZZ_TEST_CFLAGS} ${FUZZ_TEST_LDFLAGS} -o fuzz_regexp fuzz_tests/regexp.c fuzz_tests/fuzz.c -I_/include/libxml2 -L_/lib -lxml2

cifuzz:
	cifuzz bundle fuzz_xml --build-command "cd work && ./autogen.sh && ./configure --prefix=$$PWD/_ && make -j8 V=1 && make install && cd .. && make fuzzing" --clean-command "rm -f fuzz_xml fuzz_regexp fuzz_uri fuzz_xml fuzz_xpath && rm -rf _ && cd work; make clean" -v
